### ISSUE TITLE
Could I use custom deobfuscation mappings?

### ISSUE THREAD

**Issue by isXander** [Zortax/MinecraftInjectionAPI#3]
Is there a way to use custom deobfuscation mappings for custom minecraft clients like [Lunar Client](https://www.lunarclient.com/)

**Comment by skateboard** [comment]
I mean yes? just edit the [McpManager](https://github.com/zortax/MinecraftInjectionAPI/blob/master/src/main/java/de/zortax/injection/mcp/McpManager.java) ???

**Comment by zortax** [comment]
Yes, what @skateboard said, just edit the mappings parser... Although I'd recommend to just not use this at all, it's unmaintained and was just an experiment.

**Comment by skateboard** [comment]
Ya I would recommend [Mixins](https://github.com/SpongePowered/Mixin])

**Comment by laika-cosmonaut** [comment]
How would you use mixins at runtime? I can't find anything online about it. Maybe I'm just an idiot though

**Comment by skateboard** [comment]
You would have to use an agent! ive seen it done before
