### ISSUE TITLE
How do i use this..

### ISSUE THREAD

**Issue by hexlocation** [Zortax/MinecraftInjectionAPI#5]

**Comment by NathanKassab** [comment]
Ok so you're gonna wanna use the thing in your head, I think it's called something like "the brain". Once you start using your brain you should be fine to read the readme.md and determine how it works by yourself

**Comment by hexlocation** [comment]
i dont have a brain. could you explain it?

**Comment by hexlocation** [comment]
ok my brain returned to my body. now i cant get the dependency aka 
Invalid content was found starting with element '{"http://maven.apache.org/POM/4.0.0":dependency}'. One of '{"http://maven.apache.org/POM/4.0.0":parent, "http://maven.apache.org/POM/4.0.0":packaging, "http://maven.apache.org/POM/4.0.0":name, "http://maven.apache.org/POM/4.0.0":description, "http://maven.apache.org/POM/4.0.0":url, "http://maven.apache.org/POM/4.0.0":prerequisites, "http://maven.apache.org/POM/4.0.0":issueManagement, "http://maven.apache.org/POM/4.0.0":ciManagement, "http://maven.apache.org/POM/4.0.0":inceptionYear, "http://maven.apache.org/POM/4.0.0":mailingLists, "http://maven.apache.org/POM/4.0.0":developers, "http://maven.apache.org/POM/4.0.0":contributors, "http://maven.apache.org/POM/4.0.0":licenses, "http://maven.apache.org/POM/4.0.0":scm, "http://maven.apache.org/POM/4.0.0":organization, "http://maven.apache.org/POM/4.0.0":build, "http://maven.apache.org/POM/4.0.0":profiles, "http://maven.apache.org/POM/4.0.0":modules, "http://maven.apache.org/POM/4.0.0":pluginRepositories, "http://maven.apache.org/POM/4.0.0":dependencies, "http://maven.apache.org/POM/4.0.0":reports, "http://maven.apache.org/POM/4.0.0":reporting, "http://maven.apache.org/POM/4.0.0":dependencyManagement, "http://maven.apache.org/POM/4.0.0":distributionManagement}' is expected.

yes i specified the repo

**Comment by NathanKassab** [comment]
I don't think this project is actively maintained since the last readme commit was 2 years ago and the last real commit was 4. But a quick google search returned this answer, maybe it can help you
https://stackoverflow.com/questions/20765661/maven-invalid-content-was-found-starting-with-element-plugin

**Comment by NathanKassab** [comment]
If that doesn't help you then upload your pom to pastebin and send the link here, I may be able to help if I can read the whole pom

**Comment by NathanKassab** [comment]
@zortax Can we close this issue? It's been 15 days and the person who asked isn't responding

**Comment by zortax** [comment]
I mean I think it's ridiculous that so many people are still actually trying to use this.. this was just some experimentation, never supposed to actually be used for anything...

**Comment by NathanKassab** [comment]
imo it's probably best to archive the repo at this point, it's been years since the last commit and archiving would let users know that it's not actively worked on

**Comment by zortax** [comment]
but then again this is mostly used by script-kiddies trying to inject their hack client at runtime and I kind of enjoy wasting their time :P

**Comment by hexlocation** [comment]
lol ok was just experimening with this but i guess close this im not into this anymore :/
